/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pidsearch;

import java.util.Calendar;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author jethro
 */
public class GraphicsSearch extends javax.swing.JFrame {

    PIDsearch search;

    /**
     * Creates new form GraphicsSearch
     */
    public GraphicsSearch(PIDsearch s) {
        search = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromField = new javax.swing.JTextField();
        toField = new javax.swing.JTextField();
        timeField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        vyhledatBut = new javax.swing.JButton();
        fromErrorLabel = new javax.swing.JLabel();
        toErrorLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        foundPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchPanel.setDoubleBuffered(false);
        searchPanel.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Odkud:");

        jLabel2.setText("Kam:");

        jLabel3.setText("Datum:");

        jLabel4.setText("Čas:");

        fromField.setActionCommand("<Not Set>");
        fromField.setDoubleBuffered(true);
        fromField.setNextFocusableComponent(toField);

        toField.setNextFocusableComponent(timeField);

        timeField.setText("00:00");
        timeField.setNextFocusableComponent(dateField);

        dateField.setText("31.12.2013");
        dateField.setNextFocusableComponent(vyhledatBut);

        vyhledatBut.setText("Vyhledat");
        vyhledatBut.setName("null"); // NOI18N
        vyhledatBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyhledatButActionPerformed(evt);
            }
        });

        fromErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        fromErrorLabel.setText("E");

        toErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        toErrorLabel.setText("E");

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("Chyba lávky!");

        org.jdesktop.layout.GroupLayout searchPanelLayout = new org.jdesktop.layout.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(searchPanelLayout.createSequentialGroup()
                        .add(vyhledatBut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(errorLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, searchPanelLayout.createSequentialGroup()
                        .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(fromErrorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(searchPanelLayout.createSequentialGroup()
                                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel2)
                                    .add(jLabel4))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(searchPanelLayout.createSequentialGroup()
                                        .add(timeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(30, 30, 30)
                                        .add(jLabel3)
                                        .add(18, 18, 18)
                                        .add(dateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(fromField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                    .add(toField)))
                            .add(toErrorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(fromField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fromErrorLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(toField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(2, 2, 2)
                .add(toErrorLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(timeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(dateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(vyhledatBut)
                    .add(errorLabel))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parametry", searchPanel);
        jTabbedPane1.addTab("Výsledky", foundPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vyhledatButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyhledatButActionPerformed
        boolean cancel = false;
        SearchPreferences pref;
        pref = new SearchPreferences();

        System.err.println("Clicked");
        if (!search.vertexForName.containsKey(fromField.getText())) {
            fromErrorLabel.setText("Zastavka nebyla nalezena.");
            cancel = true;
        } else {
            pref.from = search.vertexForName.get(fromField.getText());
            fromErrorLabel.setText(" ");
        }
        if (!search.vertexForName.containsKey(toField.getText())) {
            toErrorLabel.setText("Zastavka nebyla nalezena.");
            cancel = true;
        } else {
            toErrorLabel.setText(" ");
            pref.to = search.vertexForName.get(toField.getText());
        }

        pref.when = Utilities.parseDate(dateField.getText());
        if (pref.when==null){
            errorLabel.setText("Chybne datum");
            cancel = true;
        } else {
        pref.when = Utilities.parseTime(timeField.getText(),pref.when);
        if (pref.when==null){
            errorLabel.setText("Chybny cas");
            cancel = true;
        }}
        

        if (cancel) {
            return;
        }
        System.err.println("Searching...");
        errorLabel.setText(pref.from.name + "->" + pref.to.name);
        pref.when = Calendar.getInstance();
        
        List<Arrival> cons;
        cons = search.search.searchConnection(pref);
        search.printConnections(cons);
    }//GEN-LAST:event_vyhledatButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final PIDsearch search) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GraphicsSearch gs;
                gs = new GraphicsSearch(search);
                gs.errorLabel.setText(" ");
                gs.fromErrorLabel.setText(" ");
                gs.toErrorLabel.setText(" ");
                Calendar cal = Calendar.getInstance();
                gs.timeField.setText(Utilities.strTime(cal));
                gs.dateField.setText(Utilities.strDate(cal));
                gs.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JScrollPane foundPanel;
    private javax.swing.JLabel fromErrorLabel;
    private javax.swing.JTextField fromField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField timeField;
    private javax.swing.JLabel toErrorLabel;
    private javax.swing.JTextField toField;
    private javax.swing.JButton vyhledatBut;
    // End of variables declaration//GEN-END:variables
}
